Avoid newlines in the middle of prefixed commit messages

diff --git a/git-hooks/commit-msg b/git-hooks/commit-msg
--- a/git-hooks/commit-msg
+++ b/git-hooks/commit-msg
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 
-# Do nothing if there is already a branch number in the commit message
-if [[ $(head -n 1 $1) =~ '[0-9]+' ]]; then
+# Do nothing if there is already a ticket number in the commit message
+if [[ $(head -n 1 $1) =~ '[HUTV' ]]; then
   exit 0
 fi
 
-# Prepend a branch number if it can be determined from the branch name
+# Prepend a ticket number if the ticket can be determined from the branch name
 BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
-REGEX="([0-9]+)"
+REGEX='HUTV-[0-9]+'
 if [[ $BRANCH_NAME =~ $REGEX ]]; then
-  BRANCH_NUM="${BASH_REMATCH[1]}"
-  echo -e "[$BRANCH_NUM] $(cat $1)" > $1
+  TASK_NUM="${BASH_REMATCH[0]}"
+  sed -i '' "1s/^/\\[$TASK_NUM\\] /" "$1"
 else
-  echo >&2 "Warning: Unable to determine branch number from branch name"
+  echo >&2 "Warning: Unable to determine ticket number from branch name"
 fi
